var fs = require('fs')
//fs.mkdirSync('ak')
//fs.writeFileSync('ak/data.txt','Hello!!')
//fs.unlinkSync('ak/data.txt')
//fs.rmdirSync('ak')
fs.writeFileSync('data1.txt','Hello!!')
fs.renameSync('data1.txt','test.txt')
a=fs.readFileSync('test.txt','utf-8')
//console.log(a.toString())
console.log(a)
fs.appendFileSync('test.txt','akshat')
fs.copyFileSync('test.txt','data2.txt')